#!/bin/sh

### BEGIN INIT INFO
# Provides:          Epicoin
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Epicoin Online Serveur
### END INIT INFO


cd /usr/local/bin/epicoin
case "$1" in
  start)
     echo "Démarrage d'epicoin server"
     mono epicoin.exe SW &
	 PID=$(ps -A -o cmd,pid | egrep "Server.exe " | head -n 1 | sed -r -e 's/.* ([0-9]+)$/\1/')
	 cpulimit -P $PID -l 50 &
     ;;
  stop)
    echo -n "Arret d'epicoin"
    ps aux | grep -i epicoin.exe | awk {'print $2'} | xargs kill
	ps aux | grep -i cpulimit | awk {'print $2'} | xargs kill
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
